"""empty message

Revision ID: 7a6b81692219
Revises: 9284b2d47673
Create Date: 2019-12-03 10:53:47.588045

"""

# revision identifiers, used by Alembic.
revision = '7a6b81692219'
down_revision = '9284b2d47673'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UnS_firma_id_fkey', 'UnS', type_='foreignkey')
    op.create_foreign_key(None, 'UnS', 'Firma', ['firma_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UnS', type_='foreignkey')
    op.create_foreign_key('UnS_firma_id_fkey', 'UnS', 'User', ['firma_id'], ['id'])
    # ### end Alembic commands ###
