"""empty message

Revision ID: 9284b2d47673
Revises: 8f73d1c3f7bb
Create Date: 2019-12-03 10:53:04.467543

"""

# revision identifiers, used by Alembic.
revision = '9284b2d47673'
down_revision = '8f73d1c3f7bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UnS', sa.Column('firma_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'UnS', 'User', ['firma_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UnS', type_='foreignkey')
    op.drop_column('UnS', 'firma_id')
    # ### end Alembic commands ###
