"""empty message

Revision ID: bfe2553147b8
Revises: 7a6b81692219
Create Date: 2019-12-03 10:58:31.703708

"""

# revision identifiers, used by Alembic.
revision = 'bfe2553147b8'
down_revision = '7a6b81692219'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Skupina', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_column('Skupina', 'id_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Skupina', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Skupina', 'name')
    # ### end Alembic commands ###
